import type { TabId, ChecklistData, AircraftRecap, ChecklistSection } from './types';

export const TABS: TabId[] = ['PAX', 'PARAMS', 'TARIFS', 'NAVS', 'RECAP', 'BUBK', 'GIYA', 'GKQA', 'GLVX', 'HMPI', 'HNNY', 'HPPL'];

export const AIRCRAFT_COLORS: Partial<Record<string, { bg: string; text: string; ring: string; border: string; highlight?: string; checkbox?: string; tableHighlight?: string; highlightText?: string; }>> = {
  PAX: { bg: 'bg-teal-500', text: 'text-white', ring: 'ring-teal-400', border: 'border-teal-500', highlight: 'bg-teal-900/50 ring-2 ring-teal-500', checkbox: 'accent-teal-500 focus:ring-teal-500', tableHighlight: 'bg-teal-500/40', highlightText: 'text-teal-400' },
  PARAMS: { bg: 'bg-purple-600', text: 'text-white', ring: 'ring-purple-500', border: 'border-purple-500' },
  TARIFS: { bg: 'bg-emerald-600', text: 'text-white', ring: 'ring-emerald-500', border: 'border-emerald-500' },
  NAVS: { bg: 'bg-pink-300', text: 'text-pink-900', ring: 'ring-pink-200', border: 'border-pink-300', highlight: 'bg-pink-200/50 ring-2 ring-pink-300', checkbox: 'accent-pink-400 focus:ring-pink-400', tableHighlight: 'bg-pink-300/40', highlightText: 'text-pink-400' },
  RECAP: { bg: 'bg-black', text: 'text-white', ring: 'ring-gray-400', border: 'border-gray-400' },
  BUBK: { bg: 'bg-orange-500', text: 'text-white', ring: 'ring-orange-400', border: 'border-orange-500', highlight: 'bg-orange-900/50 ring-2 ring-orange-500', checkbox: 'accent-orange-500 focus:ring-orange-500', tableHighlight: 'bg-orange-500/40', highlightText: 'text-orange-400' },
  GIYA: { bg: 'bg-green-500', text: 'text-white', ring: 'ring-green-400', border: 'border-green-500', highlight: 'bg-green-900/50 ring-2 ring-green-500', checkbox: 'accent-green-500 focus:ring-green-500', tableHighlight: 'bg-green-500/40', highlightText: 'text-green-400' },
  GKQA: { bg: 'bg-red-300', text: 'text-red-800', ring: 'ring-red-200', border: 'border-red-300', highlight: 'bg-red-200/50 ring-2 ring-red-300', checkbox: 'accent-red-400 focus:ring-red-400', tableHighlight: 'bg-red-600/40', highlightText: 'text-red-400' },
  GLVX: { bg: 'bg-blue-800', text: 'text-white', ring: 'ring-blue-600', border: 'border-blue-600', highlight: 'bg-blue-900/50 ring-2 ring-blue-700', checkbox: 'accent-blue-500 focus:ring-blue-500', tableHighlight: 'bg-blue-700/40', highlightText: 'text-blue-400' },
  HMPI: { bg: 'bg-sky-400', text: 'text-white', ring: 'ring-sky-300', border: 'border-sky-300', highlight: 'bg-sky-900/50 ring-2 ring-sky-400', checkbox: 'accent-sky-400 focus:ring-sky-400', tableHighlight: 'bg-sky-500/40', highlightText: 'text-sky-400' },
  HNNY: { bg: 'bg-amber-500', text: 'text-white', ring: 'ring-amber-400', border: 'border-amber-500', highlight: 'bg-amber-900/50 ring-2 ring-amber-500', checkbox: 'accent-amber-500 focus:ring-amber-500', tableHighlight: 'bg-amber-500/40', highlightText: 'text-amber-400' },
  HPPL: { bg: 'bg-yellow-400', text: 'text-gray-900', ring: 'ring-yellow-300', border: 'border-yellow-300', highlight: 'bg-yellow-900/50 ring-2 ring-yellow-400', checkbox: 'accent-yellow-400 focus:ring-yellow-400', tableHighlight: 'bg-yellow-500/40', highlightText: 'text-yellow-400' },
};

export const PARAM_PDFS: Record<string, string> = {
    'BUBK': 'https://www.aero-club-poitou.fr/acp/storage/app/media/FBUBK%20-%20Param%C3%A8tres%20V4.pdf',
    'GIYA': 'https://www.aero-club-poitou.fr/acp/storage/app/media/FGIYA%20-%20Param%C3%A8tres%20V4.pdf',
    'GKQA': 'https://www.aero-club-poitou.fr/acp/storage/app/media/FGKQA%20-%20Param%C3%A8tres%20V6.pdf',
    'GLVX': 'https://www.aero-club-poitou.fr/acp/storage/app/media/FGLVX%20-%20Param%C3%A8tres%20V4.pdf',
    'HMPI': 'https://www.aero-club-poitou.fr/acp/storage/app/media/FHMPI%20-%20Param%C3%A8tres%20V1.pdf',
    'HNNY': 'https://www.aero-club-poitou.fr/acp/storage/app/media/FHNNY%20-%20Param%C3%A8tres%20V3.pdf',
    'HPPL': 'https://www.aero-club-poitou.fr/acp/storage/app/media/FHPPL%20-%20Param%C3%A8tres%20V10.pdf'
};

export const RECAP_DATA: AircraftRecap[] = [
    {
        id: 'BUBK', shortName: 'BK',
        parametres: { rotation: '65 mi/h ou 57 kt', montee: '80 mi/h ou 70 kt', finale: '70 mi/h ou 60 kt', finesseMax: '70 mi/h ou 60 kt', vitesseCroisiere: '92 kt' },
        facteurBase: '0.65',
        cocoMax: { princ: '98 L' },
        inutilisable: { princ: '13 L' },
        conso: { perHour: '22 L/h', perMin: '0,37 L/min' },
        autonomie: { coco1: '3 h 50' },
        ventTravers: { decollage: '20 kt', atterrissage: '15 kt' },
        distances: { decollage: '422 m', atterrissage: '328 m' },
        puissance: { decollage: '2300 rpm' },
    },
    {
        id: 'GIYA', shortName: 'YA',
        parametres: { rotation: '50 kt', montee: '70 kt', finale: '60 kt', finesseMax: '60 kt', vitesseCroisiere: '101 kt' },
        facteurBase: '0.59',
        cocoMax: { princ: '142 L' },
        inutilisable: { princ: '6 L' },
        conso: { perHour: '24 L/h', perMin: '0,4 L/min' },
        autonomie: { coco1: '4 h' },
        ventTravers: { decollage: '12 kt', atterrissage: '12 kt' },
        distances: { decollage: '408 m', atterrissage: '366 m' },
        puissance: { decollage: '2150 rpm' },
    },
    {
        id: 'GKQA', shortName: 'QA',
        parametres: { rotation: '100 km/h (54 kt)', montee: '150 km/h (81 kt)', finale: '120 km/h (65 kt)', finesseMax: '150 km/h (81 kt)', vitesseCroisiere: '206 km/h (111 kt)' },
        facteurBase: '0.54',
        cocoMax: { princ: '110 L' },
        inutilisable: { princ: '10 L' },
        conso: { perHour: '30 L/h', perMin: '0,50 L/min' },
        autonomie: { coco1: '3 h 20' },
        ventTravers: { decollage: '22 kt', atterrissage: '22 kt' },
        distances: { decollage: '485 m', atterrissage: '470 m' },
        puissance: { decollage: '2300 rpm' },
    },
    {
        id: 'GLVX', shortName: 'VX',
        parametres: { rotation: '100 km/h (54 kt)', montee: '150 km/h (81 kt)', finale: '120 km/h (65 kt)', finesseMax: '150 km/h (81 kt)', vitesseCroisiere: '206 km/h (111 kt)' },
        facteurBase: '0.54',
        cocoMax: { princ: '110 L', second: '50 L' },
        inutilisable: { princ: '10 L', second: '10 L' },
        conso: { perHour: '30 L/h', perMin: '0,50 L/min' },
        autonomie: { coco1: '3 h 20', coco2: '5 h' },
        ventTravers: { decollage: '22 kt', atterrissage: '22 kt' },
        distances: { decollage: '485 m', atterrissage: '470 m' },
        puissance: { decollage: '2300 rpm' },
    },
     {
        id: 'HMPI', shortName: 'PI',
        parametres: { rotation: '50 kt', montee: '60 kt', finale: '60 kt', finesseMax: '60 kt', vitesseCroisiere: '95 kt' },
        facteurBase: '0.63',
        cocoMax: { princ: '120 L' },
        inutilisable: { princ: '2 L' },
        conso: { perHour: '20 L/h', perMin: '0,33 L/min' },
        autonomie: { coco1: '5 h 54' },
        ventTravers: { decollage: '18 kt', atterrissage: '18 kt' },
        distances: { decollage: '365 m', atterrissage: '428 m' },
        puissance: { decollage: '5000 rpm' },
    },
    {
        id: 'HNNY', shortName: 'NY',
        parametres: { rotation: '50 kt', montee: '60 kt', finale: '60 kt', finesseMax: '60 kt', vitesseCroisiere: '95 kt' },
        facteurBase: '0.63',
        cocoMax: { princ: '120 L' },
        inutilisable: { princ: '2 L' },
        conso: { perHour: '20 L/h', perMin: '0,33 L/min' },
        autonomie: { coco1: '5 h 54' },
        ventTravers: { decollage: '18 kt', atterrissage: '18 kt' },
        distances: { decollage: '365 m', atterrissage: '428 m' },
        puissance: { decollage: '5000 rpm' },
    },
    {
        id: 'HPPL', shortName: 'PL',
        parametres: { rotation: '50 kt', montee: '60 kt', finale: '60 kt', finesseMax: '60 kt', vitesseCroisiere: '95 kt' },
        facteurBase: '0.63',
        cocoMax: { princ: '120 L' },
        inutilisable: { princ: '2 L' },
        conso: { perHour: '20 L/h', perMin: '0,33 L/min' },
        autonomie: { coco1: '5 h 54' },
        ventTravers: { decollage: '18 kt', atterrissage: '18 kt' },
        distances: { decollage: '365 m', atterrissage: '428 m' },
        puissance: { decollage: '5000 rpm' },
    },
];

const navsChecklistContent: ChecklistSection[] = [
    {
      title: "PREPARATION",
      items: [],
      subsections: [
        {
          title: "CARTES VAC",
          items: [
            { item: "Points de report VFR" },
            { item: "TRACER points report carte VFR" },
            { item: "Terrains ouvert à la CAP ?" },
            { item: "Types de piste" },
            { item: "Lg de piste décollage 🛫" },
            { item: "Lg de piste atterrissage 🛬" },
            { item: "Où faire les points fixes ?" },
            { item: "Se garer où ?" },
            { item: "Contrôlé ? AFIS ? A/A ?" },
            { item: "QFU préférentiel ?" },
            { item: "altérations de cap ?" },
            { item: "SUP AIP terrains ?" },
            { item: "Taxes (atterrissage, parking, ...)" },
            { item: "ZSAR, Carte CIME / etc..." }
          ]
        },
        {
          title: "CARTE VFR",
          items: [
            { item: "Classes d'espace" },
            { item: "Zones R, D, P, ..." },
            { item: "ZIT, ZRT, TMZ, RMZ, ..." },
            { item: "Zones Para, Voltige, Câbles, ..." },
            { item: "Tracer la route" },
            { item: "RELIEF : prévoir itinéraire BIS" },
            { item: "Zmini/Zmax / Z choisie" }
          ]
        },
        {
          title: "SDVFR",
          items: [
            { item: "Tracer la navigation" },
            { item: "Renseigner tout (carburant, avion, etc...)" }
          ]
        },
        {
          title: "Carburant, Masses et Centrages",
          items: [
            { item: "Devis Carburant" },
            { item: "Devis Masses et Centrage" }
          ]
        },
        {
          title: "Destination",
          items: [
            { item: "Appeler destination" },
            { item: "Parking ?" },
            { item: "Codes entrée/sortie" },
            { item: "Horaires particulières ?" },
            { item: "Carburant ?" }
          ]
        },
        {
          title: "COUT",
          items: [
            { item: "Calcul coût du vol" },
            { item: "Coût taxes etc..." },
            { item: "Autres frais ?" }
          ]
        }
      ]
    },
    {
      title: "JOUR DU DEPART",
      items: [],
      subsections: [
        {
          title: "MATERIEL",
          items: [
            { item: "Tablette chargée" },
            { item: "Téléphone chargé" },
            { item: "Chargeurs" },
            { item: "Supports tablette / phone" },
            { item: "Cartes VAC" },
            { item: "Documents de vol + LOG NAV ..." },
            { item: "Documents avion" },
            { item: "Clés avion" },
            { item: "Carré déroutement + Docs" },
            { item: "Carte VFR" },
            { item: "Casque bis" },
            { item: "Casque de secours (/!\\ poids)" },
            { item: "Boire" },
            { item: "Manger" },
            { item: "Pipi" },
            { item: "Balises de détresse !", isWarning: true }
          ]
        },
        {
          title: "PLAN DE VOL",
          items: [
            { item: "DEPOSER PLAN DE VOL ???", isWarning: true }
          ]
        },
        {
          title: "METEO",
          items: [
            { item: "Météo complète + Vent" },
            { item: "Météo terrains arrivées" },
            { item: "METAR et TAFs terrains" }
          ]
        },
        {
          title: "INFORMATIONS DE VOL",
          items: [
            { item: "SUP AIP" },
            { item: "SUP AIP terrains" },
            { item: "NOTAMS" },
            { item: "AZBA" }
          ]
        },
        {
          title: "Carburant, Masses et Centrages",
          items: [
            { item: "Devis Carburant" },
            { item: "Devis Masses et Centrage" }
          ]
        },
        {
          title: "TEM",
          items: [
            { item: "TEM" }
          ]
        }
      ]
    }
];

const bubkChecklistContent: ChecklistSection[] = [
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'Horamètre noté' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe tirée (CHAUD)' },
        { item: 'Moteur chaud → réchauffe repoussée (FROID)' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage jaune/verte dans les 30 sec)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Bille maquette sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 1700 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée (<200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés + position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 2300 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: '500 ft/sol = phare OFF' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Bille maquette sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Batterie sur OFF' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet.aero (si utilisé)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const giyaChecklistContent: ChecklistSection[] = [
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'Horamètre noté' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe tirée (CHAUD)' },
        { item: 'Moteur chaud → réchauffe repoussée (FROID)' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage verte)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 1800 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée (<200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés + position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 2150 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Batterie sur OFF' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet.aero (si utilisé)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const gkqaChecklistContent: ChecklistSection[] = [
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Verrière fermée' },
        { item: 'Frein de parc serré' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Horamètre noté' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe carbu' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Pressions vérifiés' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage verte)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Pompe électrique sur OFF' },
        { item: 'MASTER RADIO sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Frein de parc serré' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée' },
        { item: 'Régime 1800 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée ( < 200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Voyants testés' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Verrière fermée' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Phare sur ON' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Puissance mini 2200 tr/min' },
        { item: 'TOP CHRONO Noté' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF' },
        { item: 'Pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Pompe élctrique OFF' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Frein de parc serré' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Beacon = laisser sur ON' },
        { item: 'Batterie sur OFF' },
        { item: 'Phares sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Sortir 2 crans de volets' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis (+ sondes statiques)' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet.aero (si utilisé)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const glvxChecklistContent: ChecklistSection[] = [
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Vanne réservoir auxiliaire : poussée - fermée' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Verrière fermée' },
        { item: 'Frein de parc serré' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Horamètre noté' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe carbu' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Pressions vérifiés' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage verte)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Pompe électrique sur OFF' },
        { item: 'MASTER RADIO sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Frein de parc serré' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée' },
        { item: 'Régime 1800 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée ( < 200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Voyants testés' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Verrière fermée' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Phare sur ON' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Puissance mini 2200 tr/min' },
        { item: 'TOP CHRONO Noté' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF' },
        { item: 'Pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Pompe élctrique OFF' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Frein de parc serré' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Beacon = laisser sur ON' },
        { item: 'Phares sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Batterie sur OFF' },
        { item: 'Sortir 2 crans de volets' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis (+ sondes statiques)' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet.aero (si utilisé)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const hmpiChecklistContent: ChecklistSection[] = [
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Protections d\'hélice enlevées' },
        { item: 'Protections d\'ailes enlevées' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Palonniers réglés (mettre coussin si besoin)' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Verrière fermée (2 clics)' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Avionics switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Master Switch sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Volets rentrés' },
        { item: 'Essence : ouvert sur le réservoir le MOINS plein' },
        { item: 'Réchauffe carbu si T°ext<15°C : tirée - chaud' },     
        { item: 'Clés en place, sur BOTH' },
        { item: 'Gaz TOUT REDUIT' },
        { item: 'Fuel Pump sur ON' },
        { item: 'CHOKE (starter) : moteur froid tiré comme nécessaire selon T°' },
        { item: 'Beacon sur ON' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'CHOKE (starter) repoussé lentement'},
        { item: 'Régime 2000 trs/min MAX | NE PAS DEPASSER !', isWarning:true },
        { item: 'Pression huile vérifiée (plage verte dans les 10 sec → >0.8 bar)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'PENDANT 2min NE PAS DEPASSER les 2000 trs/min !', isWarning:true },
        { item: 'Fuel Pump sur OFF (pression vérifiée)' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Avionics Switch sur ON' },
        { item: 'IC (InterCom) sur ON' },
        { item: 'Instr. (dir. Gyro - Horizon - Turn ind.) sur ON' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Horizon artificiel : cagé et maquette réglé' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Régime après 2 min : 2300 à 2500 trs/min' },
        { item: 'Voyant Charging éteint' },
        { item: 'ATIS noté' },
        { item: 'T° huile >40°C' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'SQUELCH sur auto' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
        { item: 'Aux GEN clignote' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Phare sur OFF' },
        { item: 'Régime entre 2300 et 2500 trs/min' },
        { item: 'Réservoir sur le PLUS plein' },
        { item: 'Instruments moteur : arc vert (sauf T° huile 50°C mini)' },
        { item: 'Panneau d\'alarme : vérifié éteint' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 4000 tr/min' },
        { item: 'Tests magnétos (perte 300 max | 120 entre les 2)' },
        { item: 'Réchauffe carbu testée (<100 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas | mini 1400 trs/min)' },
        { item: 'Régime 2300 à 2500 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Master Switch sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'CHOKE (starter) : repoussé | DECOLLAGE INTERDIT SI STARTER ENCLENCHE !', isWarning:true},
        { item: 'Huile = Pression / T° mini 50°C + pression dans le vert' },
        { item: 'Volets essayés + position décollage 1 cran 15° (+ message)' },
        { item: 'Verrière verrouillée (pas de message d\'alerte)' },
        { item: 'Harnais attachés' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 5000 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF + pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
        { item: 'Fuel Pump OFF' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Avionics Switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Dir. Gyro - Horieon - Turn Ind sur OFF' },
        { item: 'Régime sur ralenti' },
        { item: 'Contact magnétos : gauche maintenir 2 sec' },
        { item: 'Contact magnétos : droite maintenir 2 sec' },
        { item: 'Contact magnétos : OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Master Switch sur OFF' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Protections ailes + hélices' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet.aero (si utilisé)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const hnnyChecklistContent: ChecklistSection[] = [
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Protections d\'hélice enlevées' },
        { item: 'Protections d\'ailes enlevées' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Palonniers réglés (mettre coussin si besoin)' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Verrière fermée (2 clics)' },
        { item: 'Batterie G3X sur ON → attendre affichage GARMIN' },
        { item: 'Master Switch sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Avionics switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Crew Alerting System (EMS) : sans alerte (témoin EMS ne clignote pas)' },
        { item: 'Volets rentrés' },
        { item: 'Essence : ouvert sur le réservoir le MOINS plein' },
        { item: 'Réchauffe carbu si T°ext<15°C : tirée - chaud' },     
        { item: 'Clés en place, sur BOTH' },
        { item: 'Gaz TOUT REDUIT' },
        { item: 'Fuel Pump sur ON' },
        { item: 'CHOKE (starter) : moteur froid tiré comme nécessaire selon T°' },
        { item: 'Beacon sur ON' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'CHOKE (starter) repoussé lentement'},
        { item: 'Régime 2000 trs/min MAX | NE PAS DEPASSER !', isWarning:true },
        { item: 'Pression huile vérifiée (plage verte dans les 10 sec → >0.8 bar)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'PENDANT 2min NE PAS DEPASSER les 2000 trs/min !' , isWarning:true},
        { item: 'GEN + Aux GEN : ON - Charge vérifiée' },
        { item: 'Fuel Pump sur OFF (pression vérifiée)' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Avionics Switch sur ON' },
        { item: 'IC (InterCom) sur ON' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Affichage EFIS : EFIS (tapes) ou SIX PACK (round gauges)' },
        { item: 'Altimètre EFIS : réglé au QNH (set for field)' },
        { item: 'Altimètre de secours : réglé au QNH' },
        { item: 'Régime après 2 min : 2300 à 2500 trs/min' },
        { item: 'Voyant Charging éteint' },
        { item: 'ATIS noté' },
        { item: 'T° huile >40°C' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'SQUELCH sur auto' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
        { item: 'Aux GEN clignote' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Phare sur OFF' },
        { item: 'Régime entre 2300 et 2500 trs/min' },
        { item: 'Réservoir sur le PLUS plein' },
        { item: 'Instruments moteur : arc vert (sauf T° huile 50°C mini)' },
        { item: 'Panneau d\'alarme : vérifié éteint' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 4000 tr/min' },
        { item: 'Tests magnétos (perte 300 max | 120 entre les 2)' },
        { item: 'Réchauffe carbu testée (<100 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas | mini 1400 trs/min)' },
        { item: 'Régime 2300 à 2500 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Master Switch sur ON' },
        { item: 'GEN + Aux GEN sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'CHOKE (starter) : repoussé | DECOLLAGE INTERDIT SI STARTER ENCLENCHE !', isWarning:true},
        { item: 'Huile = Pression / T° mini 50°C + pression dans le vert' },
        { item: 'Fuel pump sur ON'},
        { item: 'Volets essayés + position décollage 1 cran 15° (+ message)' },
        { item: 'Verrière verrouillée (pas de message d\'alerte)' },
        { item: 'Harnais attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 5000 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF + pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
        { item: 'Fuel Pump OFF' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Avionics Switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'GEN + Aux GEN sur OFF' },
        { item: 'Régime sur ralenti' },
        { item: 'Contact magnétos : gauche maintenir 2 sec' },
        { item: 'Contact magnétos : droite maintenir 2 sec' },
        { item: 'Contact magnétos : OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Master Switch sur OFF' },
        { item: 'Batterie G3X sur OFF' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Protections ailes + hélices' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet.aero (si utilisé)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const hpplChecklistContent: ChecklistSection[] = [
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Protections d\'hélice enlevées' },
        { item: 'Protections d\'ailes enlevées' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Palonniers réglés (mettre coussin si besoin)' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Verrière fermée (2 clics)' },
        { item: 'Master Switch sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Avionics switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Volets rentrés' },
        { item: 'Essence : ouvert sur le réservoir le MOINS plein' },
        { item: 'Réchauffe carbu si T°ext<15°C : tirée - chaud' },     
        { item: 'Clés en place, sur BOTH' },
        { item: 'Gaz TOUT REDUIT' },
        { item: 'Fuel Pump sur ON' },
        { item: 'CHOKE (starter) : moteur froid tiré comme nécessaire selon T°' },
        { item: 'Beacon sur ON' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'CHOKE (starter) repoussé lentement'},
        { item: 'Régime 2000 trs/min MAX | NE PAS DEPASSER !', isWarning:true },
        { item: 'Pression huile vérifiée (plage verte dans les 10 sec → >0.8 bar)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'PENDANT 2min NE PAS DEPASSER les 2000 trs/min !', isWarning:true },
        { item: 'GEN + Aux GEN : ON - Charge vérifiée' },
        { item: 'Fuel Pump sur OFF (pression vérifiée)' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Avionics Switch sur ON' },
        { item: 'IC (InterCom) sur ON' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Affichage EFIS : EFIS (tapes) ou SIX PACK (round gauges)' },
        { item: 'Altimètre EFIS : réglé au QNH (set for field)' },
        { item: 'Altimètre de secours : réglé au QNH' },
        { item: 'Régime après 2 min : 2300 à 2500 trs/min' },
        { item: 'ATIS noté' },
        { item: 'T° huile >40°C' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'SQUELCH sur auto' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
        { item: 'Aux GEN clignote' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Phare sur OFF' },
        { item: 'Régime entre 2300 et 2500 trs/min' },
        { item: 'Réservoir sur le PLUS plein' },
        { item: 'Instruments moteur : arc vert (sauf T° huile 50°C mini)' },
        { item: 'Panneau d\'alarme : vérifié éteint' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 4000 tr/min' },
        { item: 'Tests magnétos (perte 300 max | 120 entre les 2)' },
        { item: 'Réchauffe carbu testée (<100 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas | mini 1400 trs/min)' },
        { item: 'Régime 2300 à 2500 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Master Switch sur ON' },
        { item: 'GEN + Aux GEN sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'CHOKE (starter) : repoussé | DECOLLAGE INTERDIT SI STARTER ENCLENCHE !', isWarning:true},
        { item: 'Huile = Pression / T° mini 50°C + pression dans le vert' },
        { item: 'Fuel pump sur ON'},
        { item: 'Volets essayés + position décollage 1 cran 15° (+ message)' },
        { item: 'Verrière verrouillée (pas de message d\'alerte)' },
        { item: 'Harnais attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 5000 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF + pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
        { item: 'Fuel Pump OFF' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Avionics Switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'GEN + Aux GEN sur OFF' },
        { item: 'Régime sur ralenti' },
        { item: 'Contact magnétos : gauche maintenir 2 sec' },
        { item: 'Contact magnétos : droite maintenir 2 sec' },
        { item: 'Contact magnétos : OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Master Switch sur OFF' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Protections ailes + hélices' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet.aero (si utilisé)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

export const paxChecklistContent: ChecklistSection[] = [
  {
    title: 'Briefing Passager',
    items: [
      { item: 'Ceintures / Harnais' },
      { item: 'Ouvertures (portes/verrières)' },
      { item: 'Malade' },
      { item: 'Aérations' },
      { item: 'Savoir piloter (expliquer)' },
      { item: 'Évacuation appareil' },
      { item: 'Commandes libres' },
      { item: 'Objets / Cabine' },
      { item: 'Urgence (IVV)' },
      { item: 'Radio / Communications' },
      { item: 'Signaler / Solliciter' },
    ]
  }
];

export const CHECKLIST_DATA: Record<TabId, ChecklistData> = {
    'PAX': {
        title: "BRIEFING PAX",
        content: paxChecklistContent,
    },
    'PARAMS': {
        title: "Paramètres",
        content: [],
    },
    'TARIFS': {
        title: "Tarifs",
        content: [],
    },
    'NAVS': {
        title: "Check-list Navs",
        content: navsChecklistContent,
    },
    'RECAP': {
        title: "Récapitulatif Performances",
        content: [],
    },
    'BUBK': { title: "Checklist F-BUBK", content: bubkChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20C150%20BK%20JFG-06-25.pdf" },
    'GIYA': { title: "Checklist F-GIYA", content: giyaChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20C150%20YA%20JFG-06-25.pdf" },
    'GKQA': { title: "Checklist F-GKQA", content: gkqaChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20DR400%20QA%20VX%20JFG-06-25.pdf" },
    'GLVX': { title: "Checklist F-GLVX", content: glvxChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20DR400%20QA%20VX%20JFG-06-25.pdf" },
    'HMPI': { title: "Checklist F-HMPI", content: hmpiChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20PI%20JFG-05-06-25.pdf" },
    'HNNY': { title: "Checklist F-HNNY", content: hnnyChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20NY%20JFG-05-06-25.pdf" },
    'HPPL': { title: "Checklist F-HPPL", content: hpplChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20PL%20JFG-06-25.pdf" },
};